package com.thezayin.generate.presentation.event

import com.thezayin.generate.domain.model.QrType

sealed class GenerateEvent {
    data class SelectType(val type: QrType) : GenerateEvent()
    data class UpdateCallNumber(val number: String) : GenerateEvent()
    data class UpdateSmsNumber(val number: String) : GenerateEvent()
    data class UpdateSmsMessage(val message: String) : GenerateEvent()
    data class UpdateEmailAddress(val address: String) : GenerateEvent()
    data class UpdateEmailSubject(val subject: String) : GenerateEvent()
    data class UpdateEmailBody(val body: String) : GenerateEvent()
    data class UpdateWebsiteUrl(val url: String) : GenerateEvent()
    data class UpdateText(val text: String) : GenerateEvent()
    data class UpdateClipboard(val clip: String) : GenerateEvent()
    data class UpdateWifiSsid(val ssid: String) : GenerateEvent()
    data class UpdateWifiPassword(val password: String) : GenerateEvent()
    data class UpdateWifiEncryption(val encryption: String) : GenerateEvent()
    data class UpdateCalendarTitle(val title: String) : GenerateEvent()
    data class UpdateCalendarDescription(val description: String) : GenerateEvent()
    data class UpdateCalendarStart(val start: String) : GenerateEvent()
    data class UpdateCalendarEnd(val end: String) : GenerateEvent()
    data class UpdateContactName(val name: String) : GenerateEvent()
    data class UpdateContactPhone(val phone: String) : GenerateEvent()
    data class UpdateContactEmail(val email: String) : GenerateEvent()
    data class UpdateLocationLat(val lat: String) : GenerateEvent()
    data class UpdateLocationLong(val long: String) : GenerateEvent()
//    data class UpdateEan8(val code: String) : GenerateEvent()
//    data class UpdateEan13(val code: String) : GenerateEvent()
//    data class UpdateUpcA(val code: String) : GenerateEvent()
//    data class UpdateUpcE(val code: String) : GenerateEvent()
    data class UpdateCode39(val code: String) : GenerateEvent()
    data class UpdateCode128(val code: String) : GenerateEvent()
    data class UpdateItf(val code: String) : GenerateEvent()
    data class UpdatePdf417(val code: String) : GenerateEvent()
    data class UpdateCodabar(val code: String) : GenerateEvent()
    data class UpdateDataMatrix(val code: String) : GenerateEvent()
    data class UpdateAztec(val code: String) : GenerateEvent()
    data object GenerateQrCode : GenerateEvent()
    data object BackPressed : GenerateEvent()
    data object DownloadQrCode : GenerateEvent()
    data object ShareQrCode : GenerateEvent()
    data object DismissDownloadSuccess : GenerateEvent()
}